### ISSUE TITLE
Fix IVASun in case of reference point change.

### ISSUE THREAD

**Issue by Mihara** [Mihara/RasterPropMonitor#61] opened 2014-01-25 16:55 UTC
The problem is this:

* When the reference point is changed while the player is in IVA, the MonoBehaviour called IVASun, which moves the spotlight that represents solar light around the IVA, gets confused, as it assumes that the reference part is the pod and that the sun needs to be rotated to match the IVA orientation *(which differs from the actual pod orientation for some unknown reason)*. When the reference part is not the pod, the extra orientation change is applied anyway, which makes the sun shine from an incorrect position.
* It is basically impossible to force the sun to move to the correct position because it happens during LateUpdate cycle, i.e. too late to do anything about it before the frame renders.
* It is, however, possible to disable the behaviour itself, and essentially reimplement it, but then I need to both compute the solar intensity, enable the light, and move it to the correct position.

I have no problem doing the enable/disable/turnlighton part, but I need help with the quaternions to move it to the correct position.

**Comment by MOARdV** [comment] 2015-10-28 02:30
Per the [Devnotes](http://forum.kerbalspaceprogram.com/threads/137725-Devnote-Tuesday-1-0-5-is-approaching) today, "A longstanding bug was fixed in the process: the orientation of the sun light in internal spaces didn’t actually match the sun direction in the outside world", it looks like KSP 1.1 will *finally* fix this bug, which corresponds (currently) with RPM v0.25.

**Comment by MOARdV** [comment] 2016-04-06 14:42
Confirmed fixed in KSP 1.1,  at last.

**Closed by MOARdV** 2016-04-06 14:42 UTC
Labels: waiting on third party
