### ISSUE TITLE
JSIAdvTransparentPods superimposes PPD-12 Cupola IVA model onto every command module (including eva kerbals)

### ISSUE THREAD

**Issue by cgruber** [Mihara/RasterPropMonitor#513] opened 2016-04-25 16:00 UTC
When JSIAdvTransparentPods is installed, rather than getting transparencies for the currently controlling command pod, I get the internals of the PPD-12 cupola superimposed.  This occurs regardless of what is currently the controlling command (including an EVA kerbal).  

I'm using this set of mods (installed by CKAN) and KSP 1.1 release.  I've tried it with a truncated list of mods and it still occurs whenever RPM has installed the JSI transparent pods. I'm going to try to replicate it with just RPM/JSI, but I have successfully worked around it by deleting (manually) the JSIAdvTransparentPods mod folder from within the RPM installation.  I can't tell if it's direclty a bug in JSI transparent pods, or an interaction. 

Mods list:

- ABCORS 0.2.0.0
- Achievements 1.9
- AutoAsparagus v2.2
- BehemothAerospaceEngineeringLargeParts 1.2.2
- BetterBurnTime 1.4.1
- BetterCrewAssignment 1.2
- CapCom 2.1
- Chatterer 0.9.8
- CommunityNavballDockingIndicator 1.0.1
- CommunityResourcePack 0.5.0.0
- CommunityTechTree 2.4.0
- ConnectedLivingSpace 1.2.0.9
- ContractConfigurator 1.10.4
- ContractConfigurator-FieldResearch 1.1.7
- ContractConfigurator-GrandTours 1:0.1.10
- ContractConfigurator-KerbinSpaceStation 1:3.2.1
- ContractConfigurator-RemoteTech 2.0.2
- ContractConfigurator-RoverMissionsRedux 0.1.3
- ContractConfigurator-UnmannedContracts 0.3.19.1
- ContractParser 2.0
- ContractsWindowPlus 6.2
- CustomBarnKit 1.1.7.0
- DMagicOrbitalScience 1.2.3
- DockingPortAlignmentIndicator 6.3
- EnvironmentalVisualEnhancements 2:EVE-1.1-1
- EnvironmentalVisualEnhancements-HR 2:EVE-1.1-1
- ETT 1:v20160205
- ExtraPlanetaryLaunchpads 5.3.0
- FilterExtensions 2.5.0
- FilterExtensionsDefaultConfig 2.5.0
- FirespitterCore v7.2.1
- InterstellarFuelSwitch 1.24
- InterstellarFuelSwitch-Core 1.24
- Karbonite 1:0.7.1.0
- KaribouExpeditionRover 0.2.1.0
- KAS 0.5.6
- KerbalEngineerRedux 1.1.0.2
- KerbalJointReinforcement v3.1.5
- KerbalPlanetaryBaseSystems v1.0.8
- KIS 1.2.7
- Kopernicus 2:release-1-0-2
- KSP-AVC 1.1.6.1
- KSPInterstellarExtended 1.8.12
- KSPSteamCtrlr autodetected dll
- LandingHeight 1.5
- LaunchNumbering 0.2.0
- MechJeb2 2.5.7.0
- MiniAVC 1.0.3.0
- Mk2Expansion 1.7.03
- Mk3HypersonicSystems 1.1.0.1
- ModuleManager 2.6.23
- NavballUpDefault v0.2.2
- OrbitalTug 1.1
- PlanetShine 1:0.2.5
- PlanetShine-Config-Default 1:0.2.5
- PrakasaAeroworks 0.4
- ProgressParser 3.0
- RasterPropMonitor 1:v0.25.1.28297b
- RasterPropMonitor-Core 1:v0.25.1.28297b
- RCSSounds 5.0.1
- RemoteTech v1.6.11
- REPOSoftTech-Agencies V1.2.0.0
- SaveUpgradePipeline autodetected dll
- SCANsat v16.0
- Service-Compartments-6S 1.3
- SixCrewScienceLab 1.1
- SoundingRockets 0.4.1.0
- SpacetuxSA 0.3.9.0
- SpaceY-Expanded 1.1.7
- SpaceY-Lifters 1.12.1
- StageRecovery autodetected dll
- Steamworks autodetected dll
- Strategia 1.2.1
- TarsierSpaceTechnologyWithGalaxies 1:6.0
- ThrottleControlledAvionics v3.0.1-KSP-1.1-BETA
- Toolbar 1.7.11
- TweakScale v2.2.7.2
- UKS 1:0.40.1.1
- USI-ART 1:0.8.1.0
- USI-Core 0.2.1.0
- USI-EXP 0.5.1.0
- USI-FTT 0.5.1.0
- USI-LS 0.4.2.0
- USI-NuclearRockets 0.2.1.0
- USI-SRV 0.5.1.0
- USITools 0.7.1.0
- USI-UKS-Shared 0.2.1.0
- WaypointManager 2.5.0

**Comment by JPLRepo** [comment] 2016-04-25 23:55
No log, can't help much. Does not occur for me with the current release version. not about to install all those mods to figure out which one it is. but I am guessing something is getting changed by one of these mods.

**Comment by cgruber** [comment] 2016-04-26 16:45
Sorry - I'll find a log.  I'm quite sure something is being changed by the mods.  I'm trying it with a variety of different mods to see what interacts.  Just game-loading time takes a while.

**Comment by JPLRepo** [comment] 2016-04-26 19:43
I've had a thought. I think what we might have here is a mod using the old JSITransparentPod module. JSITransparentPod module and the new JSIAdvTransparentPod module are not compatible. JSITransparenPod should be deprecated. I'm following up with @MOARdV on the best approach. My thoughts are to disable the old module (but still have it there) so old mods won't fail but won't have transparent pods until their authors make the changes to switch to the new module.

**Comment by justinpstarr** [comment] 2016-04-26 19:58
Having the exact same issues on a heavily modded CKAN install.  Here is a link to my logs.  
[https://www.dropbox.com/sh/dxd9vmxko5jbe12/AAD4a-hKeDj47MhXZpif6FE3a?dl=0](https://www.dropbox.com/sh/dxd9vmxko5jbe12/AAD4a-hKeDj47MhXZpif6FE3a?dl=0)

Sorry still learning otherwise I would dig through and grab some useful info.

**Comment by justinpstarr** [comment] 2016-04-26 20:08
After searching there are references to both JSITransparentPod and JSIAdvTransparentPod, but I do not understand the logs enough yet to tell what is calling JSITransparentPod.

**Comment by MOARdV** [comment] 2016-04-26 20:20
@justinpstarr - That indicates that the latest RPM update was installed over an existing install.  There's a MM config from previous installations.  The log also has a *lot* of exceptions that indicate there is at least one DLL installed that has not been updated to KSP 1.1.  Those exceptions can cause all sorts of oddball errors, so one of the first steps needs to be going through and making sure the only DLLs installed are those which have been updated to KSP 1.1.

Actually, I see one major problem - you have a second installation under GameData/Mk3HypersonicSystems - I don't know if that was a bad installation of that mod, or something that copied accidentally, but there's a second copy of ModuleManager, Firespitter, and RasterPropMonitor in that directory.

**Comment by justinpstarr** [comment] 2016-04-26 20:25
@MOARdV Thanks for looking.  I appears that MK3 Hypersonic installs several mods nested within itself.  I am removing them now as well as ensuring a clean install of the RPM mod by removing from CKAN and then deleting the JSI directory.  Is that enough?
I will let you know how it goes.

**Comment by MOARdV** [comment] 2016-04-26 20:29
@justinpstarr - that should be enough.  There may be some other mods that are playing badly, but I'd start there.

**Comment by justinpstarr** [comment] 2016-04-26 20:37
@MOARdV Well that fixed it.  I removed the Mk3 Hypersonic Mod completely.  I will go back and ReAdd and then remove the sub directories.  Or just not use it. =)  Thanks again for all your hard work and time you all put into this.  I hope to be as cool as you guys when I grow up.

**Comment by JPLRepo** [comment] 2016-04-26 20:49
@justinpstarr  Please advise if you still are encountering the error once you have cleaned up your install so this issue can be closed. As @MOARdV  said your install is a mess with mods installed over old versions, mods that look like they don't support 1.1. etc.
@cgruber  - you may want to look at the same. But as you haven't supplied a log, can't be sure.

**Comment by justinpstarr** [comment] 2016-04-26 20:52
@JPLRepo Yes this did fix the issue.  MK3SuperSonicSystems as being installed by CKAN was also installing another copy of RPM, Firespitter, and ModuleManager. So that was causing all kind of crap.  I have reported the issue to Plague006 on the CKAN IRC channel and they are looking into it.

Thanks again.

**Comment by JPLRepo** [comment] 2016-04-26 21:10
Leave this open until @cgruber responds in same.

**Comment by justinpstarr** [comment] 2016-04-26 21:12
@JPLRepo The CKAN install of MK3SupersonicSystems has been fixed, and is no longer causing this.

**Comment by MOARdV** [comment] 2016-04-26 22:17
@cgruber 's modlist also include Mk3 Hypersonic Systems, so I strongly suspect the same root cause.

**Comment by MOARdV** [comment] 2016-04-28 20:10
Closing based on lack of further info.

**Closed by MOARdV** 2016-04-28 20:10 UTC
Labels: works for me
