### ISSUE TITLE
Add master switch option to JSIActionGroupSwitch

### ISSUE THREAD

**Issue by MOARdV** [Mihara/RasterPropMonitor#169] opened 2015-04-29 01:13 UTC
Placeholder bug ... Note to self: go back and find the bug description.  Sumghai saw a problem with multiple props in a part not behaving right.

**Comment by sumghai** [comment] 2015-04-29 01:40
For your convenience, here's the detailed bug report :D

**JSIActionGroupSwitch does not work on multiple instances of an animated prop**

In my FusTek Station Parts add-on, I have a **CurvedWallPadded_Viewport** internal prop that uses JSIActionGroupSwitch to animate the opening and closing of a integrated window privacy/blast shutter.

At the moment, CurvedWallPadded_Viewport is defined *once* in the Props folder, and multiple instances of the prop are instantiated when putting together IVAs for Habitation, Science and Utilities modules.

Unfortunately, RasterPropMonitor (which provides JSIActionGroupSwtich) does not appear to be able to handle multiple instances of the same animated prop - for instance, the Hab module has six of these viewports, but only the one defined last in the Hab's Internals.CFG file (which happens to be the one next to one of the sleeping areas) can actually be toggled - the other five viewport shutters are non-responsive.

**Comment by sumghai** [comment] 2015-04-29 01:46
Just a heads-up for MOARdV:

At the time of writing, I've temporarily commented out the JSIActionGroupSwitch in  CurvedWallPadded_Viewport.cfg, but the animation itself (**ViewportShutterMove**) still exists in the corresponding model. You'll need to uncomment that bit in the CFG to diagnose the problem.

**Comment by MOARdV** [comment] 2015-04-29 13:58
Here's my initial diagnosis: JSIActionGroupSwitch animations are tied only to the prop the switch is on.  It doesn't look at other props at all.  That said, I am sure Mihara had a way to control animations off-prop - Bobcat used it on some of his pods.  I am going to need to dig through the code and wiki to see what I can find - it's been a long time since I looked closely at this area of RPM.

**Comment by MOARdV** [comment] 2015-04-29 14:05
Okay, that was easy.
```
      perPodPersistenceName = viewportControl
```
needs to be in the prop's JSIActionGroupSwitch module.  You can name the persistence name anything you like - any JSIActionGroupSwitch part that has that name will be controllable from the switch (you can even have a remote switch separate from the viewport panels).

**Comment by sumghai** [comment] 2015-04-29 19:27
Sorry, I forgot to mention a critical detail:

My intention was to make each instance of the prop individually toggleable, as well as implementing some sort of master switch elsewhere later on.

Would perPodPersistence be of any help with making them individually toggleable?

**Comment by sumghai** [comment] 2015-04-29 22:20
Elaboration on use cases:

 - Using the Hab module as an example, the window shutters are found in the individual sleeping compartments and the galley area. The shutters need to be individually toggleable so that the Kerbal in the sleeping compartment can close his/her own window shutter, while the other Kerbals sitting in the galley can continue to admire the view of the cosmos through their own (open) shutters.

 - The master switch feature that opens or closes all shutters simultaneously would be used in an emergency when micrometeorite impacts / solar flare events / Duna dust storms are imminent. This might call for a special Fustek Station Management plugin that automatically tells all FusTek modules to "batten down the hatches" in such a situation.

**Comment by MOARdV** [comment] 2015-04-30 02:07
perPodPersistence creates an interrelation between the components such that if you toggle one of the switches, you toggle them all.  I think, from your description, your goal is this: if master switch is "OPEN", the individual switches can toggle open/closed at their whim.  If the master switch is "CLOSED", the shutters all close, regardless of the local switches.  RPM currently can't do that - what you're looking for is a way to query a local per-shutter switch state, and do a logical AND with a master switch setting, right?  I can dig into the RPM code to see if I can support it, but I can't make a guarantee on the result just yet.

**Comment by sumghai** [comment] 2015-04-30 02:11
> what you're looking for is a way to query a local per-shutter switch state, and do a logical AND with a master switch setting, right?

Ideally, yeah.

But let's put the master switch feature idea aside for now - we should probably try making each instance of the viewport *independently* toggleable first :)

**Comment by MOARdV** [comment] 2015-04-30 12:03
Ah - I may have overlooked that aspect of the description.  Right now, only one prop's switch works?  I could not operate the left window in the Utilities pod (left from the crew seat viewpoint), but I thought that was because there as something blocking the collider, since I had trouble finding the right window's button / switch.

**Comment by MOARdV** [comment] 2015-04-30 13:16
I found the collider on the left window, and I can independently toggle the two portals.  My problem was figuring out where to click.  From the right seat in the Utilities module, I have to click towards the rear of the box on the right bulkhead to toggle the window, but I have to click near the bottom of the left window's box.  Slightly higher than that, and a double-click switches me to the "peer out the window" camera.  How do you have the colliders set up for the button and the "switch viewpoint" hit box?  It looks like there's a gray/white box, but there's no obvious switch or button on it, so I was fumbling around to find the hit boxes for the switch.

**Comment by sumghai** [comment] 2015-04-30 20:36
So the problem is with a awkwardly-sized collider?

I have an invisible collider box right over the CLICK ME! text, as a placeholder interaction hit box - the final version will have a integrated switch panel with a functional SHUTTER button and a dummy DEMIST button.

I'll upload a screenshot later tonight showing how the prop is configured in Unity (showing the model hierarchy and colliders), as this may help determine whether my hit boxes are too shallow.

**Comment by MOARdV** [comment] 2015-05-01 00:55
Here's what I see in game (Utilities module, right seat).  I've drawn a red box around what seems to be the collider.  I didn't see any markings.  I grabbed this snapshot with the model from GitHub on 4/29 in the morning my time (it would've been about 14:00 UTC on 4/29, so probably some time next week for those people on the other side of the 180th meridian :) ).

![screenshot13](https://cloud.githubusercontent.com/assets/6089493/7425217/76af1ab8-ef72-11e4-8d70-88ee0657963a.png)

**Comment by sumghai** [comment] 2015-05-01 01:19
Ah, I see - that entire grey cuboid is supposed to be the (temporary) hitbox for toggling the shutters.

I'll still post the screenshots of my Unity stuff tonight, but I suspect that maybe the "peer out the window" hitbox is either intersecting or blocking access to the shutter hitbox.

**Comment by sumghai** [comment] 2015-05-01 08:13
Yep, you and I were right - the "peer out the window" hitbox is too big and is interfering with the shutter toggle:

![1](https://cloud.githubusercontent.com/assets/4993380/7428039/f75752c8-f03c-11e4-8562-1fb6d2eef511.PNG)
**Fig 1** - Unity GameObject hierarchy of viewport prop

![2](https://cloud.githubusercontent.com/assets/4993380/7428072/7a9b828a-f03d-11e4-84e3-facba1b05ca8.PNG)
 **Fig 2** - Unity 3D view of viewport prop model

![3](https://cloud.githubusercontent.com/assets/4993380/7428085/c28af6f2-f03d-11e4-8ffa-2b2c7dc25053.PNG)
**Fig 3** - Utilities module internals overlaid with position of viewport prop*

*I wasn't able to load the full IVA in Unity, due to an asset duplication bug with PartTools that Mu is aware of.

I think the solution is plain as day - I'll need to use smaller cuboids or a cylinder mesh collider for the "peer out the window" hitboxes instead, so that they don't overlap with the shutter toggle collider.

Thanks for the help, MOARdV - feel free to decide if you want to implement the master/slave prop animation control feature :)

**Comment by MOARdV** [comment] 2015-05-01 17:22
I'm glad it was an "easy" bug.  As for the master/slave feature, I think an implementation like I described earlier will be easy to do.  I'll do some experimentation using your IVA with a big, ugly switch hacked onto the bulkhead for testing purposes, and I'll let you know when / if I have something workable.

**Comment by MOARdV** [comment] 2015-05-05 13:33
Since the initial bug is understood as a collider problem, I'll repurpose this issue as a feature request for the master switch functionality discussed in this thread.

**Comment by sumghai** [comment] 2015-05-05 20:27
Aye, thanks :)

There are two ways I'd like to be able to trigger this master switch feature:

 - Using a JSI RPM button in IVA (as is the case for RPM-powered props)

 - Some sort of API to allow plugin authors to interface this feature with a standalone plugin (
     - **use case:** *I'll get someone to write a standalone FusTek station management plugin, which will provide a standalone UI in the flight scene. A toggle button marked "Open/Close All Shutters will search for all FusTek parts on an active vessel, and open/close all shutters on all modules accordingly.*

**Comment by MOARdV** [comment] 2015-05-09 16:04
I'll need to think on this some more - for now, bumping to the next release.

**Comment by MOARdV** [comment] 2015-05-15 23:25
A new configuration field `perPodMasterSwitchName` tells a JSIActionGroupSwitch the name of a master switch's per-pod global variable.  When the master switch is off, the local switch is disabled (and, if it was on, it's set to off).  The master switch will need to be configured with a 'dummy' action and a perPodPersistenceName that matches the master switch name (although it might work with plugin actions, too).

**Closed** 2015-05-17 02:53 UTC
Labels: minor feature

**Comment by sumghai** [comment] 2015-05-17 06:51
Excellent, thanks! :)
