### ISSUE TITLE
[Linux] [1.3.x] Purple bars where characters should be 

### ISSUE THREAD

**Issue by SirRolls** [Mihara/RasterPropMonitor#637] opened 2017-07-11 00:37 UTC
Might be related to the shaders not working, but where ever a character should be, or even graphs, there is just a purple bar. Running linux mint, cinnamon

**Comment by MOARdV** [comment] 2017-07-11 00:52
This is a duplicate of Issue #634 .  Note that I posted a test build today in the RPM thread that may have fixed this issue.  You do not indicate which version of RPM you were using.

**Comment by SirRolls** [comment] 2017-07-11 00:58
Running RPM Build #11864 beta 3. I'll try the test build ITT now

**Comment by SirRolls** [comment] 2017-07-11 01:09
Test build works for me!

**Comment by MOARdV** [comment] 2017-07-11 12:05
Closing as a duplicate.  Thank you for the feedback.

**Closed by MOARdV** 2017-07-11 12:05 UTC
Labels: bug, duplicate
