### ISSUE TITLE
SI format and JSIVariableLabel

### ISSUE THREAD

**Issue by Alexustas** [Mihara/RasterPropMonitor#506] opened 2016-04-23 18:39 UTC
I am having problems using the SI-format in JSIVariableLabel

![screenshot46](https://cloud.githubusercontent.com/assets/6713671/14763334/45b42392-09b4-11e6-8b1a-5a83b44e56b8.png)

```
[EXC 00:13:50.926] NullReferenceException: Object reference not set to an instance of an object
	JSI.StringProcessor.ProcessString (JSI.StringProcessorFormatter formatter, JSI.RPMVesselComputer comp)
	JSI.JSIVariableLabel.OnUpdate ()
	InternalProp.OnUpdate ()
	InternalModel.OnUpdate ()
	Part.InternalOnUpdate ()
	Part.Update ()
```

config:

>	MODULE
	{
		name = JSIVariableLabel
		transformName = DigitIndicatorAmountObj
		fontSize = 0.020
		refreshRate = 10
		labelText = [#fff600ff] <=0:SIP6.3=>$&$DYNAMICPRESSURE 
	}

KSP 1.1.0.1230 (x64)
RPM 0.25.1.25955

**Comment by MOARdV** [comment] 2016-04-23 20:44
Stupid mistake on my part, and I didn't have any JSIVariableLabel that use SI formatting, so I didn't catch it.  Fixed in [Hotfix 26155](https://github.com/Mihara/RasterPropMonitor/releases/tag/v0.25.1.26155).

**Comment by Alexustas** [comment] 2016-04-23 20:59
SI formatting is fixed now. But I still have NullReferenceException

```
[EXC 02:50:52.952] NullReferenceException: Object reference not set to an instance of an object
	JSI.StringProcessor.ProcessString (JSI.StringProcessorFormatter formatter, JSI.RPMVesselComputer comp)
	JSI.JSIVariableLabel.OnUpdate ()
	InternalProp.OnUpdate ()
	InternalModel.OnUpdate ()
	Part.InternalOnUpdate ()
	Part.Update ()

**Comment by Alexustas** [comment] 2016-04-23 21:01
ksp.log
https://www.dropbox.com/s/z7wu9fz42j7z2jv/KSP.log?dl=0

**Comment by MOARdV** [comment] 2016-04-23 22:16
Ah, a second bug caused by an exception in JSIVariableLabel.Start.  Two or three bugs for the price of one.  [Hotfix 28297](https://github.com/Mihara/RasterPropMonitor/releases/tag/v0.25.1.28297)

**Comment by Alexustas** [comment] 2016-04-23 22:22
excellent! the problem is solved. everything works perfectly

**Closed** 2016-04-27 12:08 UTC
Labels: bug, implemented/fixed
